# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return A scalar. 
tr <- function(A) {
    .Call('_MNR_tr', PACKAGE = 'MNR', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return A numeric matrix. 
fastMMp <- function(A, B) {
    .Call('_MNR_fastMMp', PACKAGE = 'MNR', A, B)
}

#' Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
fastT <- function(A) {
    .Call('_MNR_fastT', PACKAGE = 'MNR', A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return A numeric matrix. 
fastIP <- function(A, B) {
    .Call('_MNR_fastIP', PACKAGE = 'MNR', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return A numeric matrix. 
fastInv <- function(A) {
    .Call('_MNR_fastInv', PACKAGE = 'MNR', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return A scalar. 
fastDet <- function(A) {
    .Call('_MNR_fastDet', PACKAGE = 'MNR', A)
}

#' Fast Outer Product
#' 
#' Calculates the outer product \eqn{xy'}.
#' 
#' @param x Numeric vector.
#' @param y Numeric vector.
#' @return Numeric matrix.
fastOP <- function(x, y) {
    .Call('_MNR_fastOP', PACKAGE = 'MNR', x, y)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
fastQF <- function(X, A) {
    .Call('_MNR_fastQF', PACKAGE = 'MNR', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}}. 
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @return A numeric matrix. 
#'
SchurC <- function(I11, I22, I12) {
    .Call('_MNR_SchurC', PACKAGE = 'MNR', I11, I22, I12)
}

