# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bivariate Parameter Update
#' 
#' Parameter update for bivariate outcome model.
#' 
#' @param yt Target outcome
#' @param ys Surrogate outcome
#' @param Zt Target design
#' @param Zs Surrogate design
#' @param At Target inc. proj.
#' @param As Surrogate inc. proj.
#' @param b0 Current beta
#' @param a0 Current alpha
#' @param s0 Current sigma
#' @export 
updateBVR <- function(yt, ys, Zt, Zs, At, As, b0, a0, s0) {
    .Call('_MNR_updateBVR', PACKAGE = 'MNR', yt, ys, Zt, Zs, At, As, b0, a0, s0)
}

#' Sparse Kronecker Product
#' 
#' Forms the product \eqn{I_{n\times n}\otimes A}.
#' 
#' @param n Dimension of identity matrix
#' @param A Numeric matrix
sKroneckerP <- function(n, A) {
    .Call('_MNR_sKroneckerP', PACKAGE = 'MNR', n, A)
}

#' Fast Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
#' @export
fastT <- function(A) {
    .Call('_MNR_fastT', PACKAGE = 'MNR', A)
}

#' Fast Matrix Inner Product
#'
#' Calculates \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @export
fastIP <- function(A, B) {
    .Call('_MNR_fastIP', PACKAGE = 'MNR', A, B)
}

#' Fast Matrix Inverse
#'
#' @param A Numeric matrix.
#' @export
fastInv <- function(A) {
    .Call('_MNR_fastInv', PACKAGE = 'MNR', A)
}

#' Fast Matrix Determinant
#'
#' Calculates \eqn{\det(A)}.
#'
#' @param A Numeric matrix.
#' @export
fastDet <- function(A) {
    .Call('_MNR_fastDet', PACKAGE = 'MNR', A)
}

#' Fast Quadratic Form
#' 
#' Calculates \eqn{x'Ax}.
#' 
#' @param x Numeric vector.
#' @param A Numeric matrix.
#' @export
fastQF <- function(x, A) {
    .Call('_MNR_fastQF', PACKAGE = 'MNR', x, A)
}

#' Incomplete projection
#' 
#' Form the incomplete projection \eqn{(A'A)^{-1}A};
#' 
#' @param A Numeric matrix
#' @export
incP <- function(A) {
    .Call('_MNR_incP', PACKAGE = 'MNR', A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}};
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @export
#'
SchurC <- function(I11, I22, I12) {
    .Call('_MNR_SchurC', PACKAGE = 'MNR', I11, I22, I12)
}

#' Multivariate Parameter Update
#' 
#' Parameter update for multivariate outcome model.
#' 
#' @param yt Target outcome
#' @param S Surrogate outcome vector
#' @param Zt Target design
#' @param Zs Surrogate design
#' @param At Target inc. proj.
#' @param b0 Current beta
#' @param a0 Current alpha
#' @param s0 Current sigma
#' @export 
updateMNR <- function(yt, S, Zt, Zs, At, b0, a0, s0) {
    .Call('_MNR_updateMNR', PACKAGE = 'MNR', yt, S, Zt, Zs, At, b0, a0, s0)
}

#' Information
#'
#' Calculate \eqn{A'(I_{n\times n}\otimes L)B}, the general form of information matrices
#' for the multivariate outcome model. 
#'
#' @param n Observations
#' @param A Left hand matrix
#' @param B Right hand matrix
#' @param L Precision
#' @export 
infoMNR <- function(n, A, B, L) {
    .Call('_MNR_infoMNR', PACKAGE = 'MNR', n, A, B, L)
}

