# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar.
#' @export  
tr <- function(A) {
    .Call('_MNR_tr', PACKAGE = 'MNR', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
#' @export 
MMP <- function(A, B) {
    .Call('_MNR_MMP', PACKAGE = 'MNR', A, B)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matIP <- function(A, B) {
    .Call('_MNR_matIP', PACKAGE = 'MNR', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matInv <- function(A) {
    .Call('_MNR_matInv', PACKAGE = 'MNR', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @return Scalar. 
#' @export 
det <- function(A) {
    .Call('_MNR_det', PACKAGE = 'MNR', A)
}

#' Fast Outer Product
#' 
#' Calculates the outer product \eqn{XY'}.
#' 
#' @param X Numeric matrix.
#' @param Y Numeric matrix.
#' @return Numeric matrix.
#' @export 
matOP <- function(X, Y) {
    .Call('_MNR_matOP', PACKAGE = 'MNR', X, Y)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{X'AX}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @return Numeric matrix. 
#' @export 
matQF <- function(X, A) {
    .Call('_MNR_matQF', PACKAGE = 'MNR', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{bb}-I_{ba}I_{aa}^{-1}I_{ab}}. 
#'
#' @param Ibb Information of target parameter
#' @param Iaa Information of nuisance parameter
#' @param Iba Cross information between target and nuisance parameters
#' @return Numeric matrix. 
#' @export 
SchurC <- function(Ibb, Iaa, Iba) {
    .Call('_MNR_SchurC', PACKAGE = 'MNR', Ibb, Iaa, Iba)
}

